# Generated by Django 4.2 on 2023-04-26 18:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adddrug',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=100)),
                ('category', models.CharField(default='', max_length=100)),
                ('price_start', models.IntegerField(default=0)),
                ('prices_end', models.IntegerField(default=0)),
                ('date_of_entering', models.DateTimeField(default=datetime.datetime(2023, 4, 26, 13, 0, 0, 984720))),
                ('date_of_ending', models.DateField()),
                ('pricee', models.IntegerField(default=0)),
                ('desc', models.CharField(max_length=300)),
                ('image', models.ImageField(upload_to='photoproduct/%y/%m/%d')),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
