# Generated by Django 4.2 on 2023-04-27 00:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adddrug',
            options={'verbose_name': 'main', 'verbose_name_plural': 'mains'},
        ),
        migrations.AddField(
            model_name='adddrug',
            name='slug',
            field=models.SlugField(blank=True, null=True, verbose_name='url'),
        ),
        migrations.AlterField(
            model_name='adddrug',
            name='date_of_entering',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 26, 19, 14, 0, 953126)),
        ),
    ]
