# Generated by Django 4.2 on 2023-04-27 01:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_adddrug_options_adddrug_slug_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adddrug',
            old_name='slug',
            new_name='sluga',
        ),
        migrations.RemoveField(
            model_name='adddrug',
            name='pricee',
        ),
        migrations.AlterField(
            model_name='adddrug',
            name='date_of_entering',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 26, 20, 32, 14, 523541)),
        ),
    ]
