# Generated by Django 4.2 on 2023-04-30 05:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_adddrug_date_of_entering'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adddrug',
            name='sluga',
        ),
        migrations.AlterField(
            model_name='adddrug',
            name='date_of_entering',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 30, 0, 0, 28, 200283)),
        ),
        migrations.AlterField(
            model_name='adddrug',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='photoproduct/%y/%m/%d'),
        ),
    ]
