# Generated by Django 4.2 on 2023-04-30 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_adddrug_sluga_alter_adddrug_date_of_entering_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Adddrug',
        ),
    ]
