# Generated by Django 4.2 on 2023-04-30 18:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0006_delete_adddrug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adddrug',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=100, verbose_name='اسم المنتج')),
                ('category', models.CharField(default='', max_length=100)),
                ('desc', models.CharField(max_length=500)),
                ('unit_big', models.CharField(blank=True, max_length=100, null=True)),
                ('num_of_big_unit', models.IntegerField(blank=True, default=0, null=True)),
                ('num_of_big_medium', models.IntegerField(blank=True, default=0, null=True)),
                ('num_of_medium_small', models.IntegerField(blank=True, default=0, null=True)),
                ('cost_of_big', models.IntegerField(blank=True, default=0, null=True)),
                ('price_of_big', models.IntegerField(blank=True, default=0, null=True)),
                ('unit_medium', models.CharField(blank=True, max_length=100, null=True)),
                ('num_of_medium_unit', models.IntegerField(blank=True, default=0, null=True)),
                ('cost_of_medium', models.IntegerField(blank=True, default=0, null=True)),
                ('price_of_medium', models.IntegerField(blank=True, default=0, null=True)),
                ('unit_small', models.CharField(max_length=100)),
                ('num_of_small_unit', models.IntegerField(blank=True, default=0, null=True)),
                ('cost_of_small', models.IntegerField(default=0)),
                ('price_of_small', models.IntegerField(default=0)),
                ('date_of_entering', models.DateTimeField(default=datetime.datetime(2023, 4, 30, 13, 17, 32, 760337))),
                ('date_of_ending', models.DateField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='photoproduct/%y/%m/%d')),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'main',
                'verbose_name_plural': 'mains',
            },
        ),
    ]
