# Generated by Django 4.2 on 2023-04-30 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Adddrug',
        ),
    ]
