# Generated by Django 4.2 on 2023-04-30 19:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0008_delete_adddrug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adddrug',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=100, verbose_name='اسم المنتج')),
                ('category', models.CharField(default='', max_length=100, verbose_name='الفئة')),
                ('desc', models.CharField(max_length=500, verbose_name='الوصف')),
                ('currency', models.CharField(max_length=500, verbose_name='العملة')),
                ('unit_big', models.CharField(blank=True, max_length=100, null=True, verbose_name='الوحدة الكبيرة')),
                ('num_of_big_unit', models.IntegerField(blank=True, default=0, null=True, verbose_name='عدد الوحدات الكبيرة')),
                ('num_of_big_medium', models.IntegerField(blank=True, default=0, null=True, verbose_name='عدد الوحدات المتوسطة داخل الوحدة الكبيرة')),
                ('num_of_medium_small', models.IntegerField(blank=True, default=0, null=True, verbose_name='عدد الواحدات الصغيرة التي تحتويها الوحدة المتوسطة')),
                ('cost_of_big', models.IntegerField(blank=True, default=0, null=True, verbose_name='تكلفة الوحدة الكبيرة')),
                ('price_of_big', models.IntegerField(blank=True, default=0, null=True, verbose_name='سعر الوحدة الكبيرة')),
                ('unit_medium', models.CharField(blank=True, max_length=100, null=True, verbose_name='الوحدة المنوسطة')),
                ('num_of_medium_unit', models.IntegerField(blank=True, default=0, null=True, verbose_name='عدد الوحدات المتوسطة')),
                ('cost_of_medium', models.IntegerField(blank=True, default=0, null=True, verbose_name='تكلغة الوحدة المتوسطة')),
                ('price_of_medium', models.IntegerField(blank=True, default=0, null=True, verbose_name='سعر الوحدة المتوسطة')),
                ('unit_small', models.CharField(max_length=100, verbose_name='الوحدة الصغيرة')),
                ('num_of_small_unit', models.IntegerField(blank=True, default=0, null=True, verbose_name='عدد الوحدات الصغيرة')),
                ('cost_of_small', models.IntegerField(default=0, verbose_name='تكلغة الوحدة الصغيرة')),
                ('price_of_small', models.IntegerField(default=0, verbose_name='سعر الوحدة الصغيرة')),
                ('date_of_entering', models.DateTimeField(default=datetime.datetime(2023, 4, 30, 14, 33, 1, 386329), verbose_name='تاريخ الإدخال')),
                ('date_of_ending', models.DateField(verbose_name='تاريخ انتهاء الصلاحية')),
                ('image', models.ImageField(blank=True, null=True, upload_to='photoproduct/%y/%m/%d', verbose_name='صورة المنتج')),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'main',
                'verbose_name_plural': 'mains',
            },
        ),
    ]
