# Generated by Django 4.2 on 2023-05-06 15:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_billsale_alter_adddrug_date_of_entering'),
    ]

    operations = [
        migrations.AddField(
            model_name='billsale',
            name='name_of_product2',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='اسم المنتج'),
        ),
        migrations.AddField(
            model_name='billsale',
            name='name_of_product3',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='اسم المنتج'),
        ),
        migrations.AddField(
            model_name='billsale',
            name='name_of_product4',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='اسم المنتج'),
        ),
        migrations.AddField(
            model_name='billsale',
            name='name_of_product5',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='اسم المنتج'),
        ),
        migrations.AddField(
            model_name='billsale',
            name='name_of_product6',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='اسم المنتج'),
        ),
        migrations.AddField(
            model_name='billsale',
            name='num_of_units2',
            field=models.IntegerField(blank=True, null=True, verbose_name='العدد'),
        ),
        migrations.AddField(
            model_name='billsale',
            name='num_of_units3',
            field=models.IntegerField(blank=True, null=True, verbose_name='العدد'),
        ),
        migrations.AddField(
            model_name='billsale',
            name='num_of_units4',
            field=models.IntegerField(blank=True, null=True, verbose_name='العدد'),
        ),
        migrations.AddField(
            model_name='billsale',
            name='num_of_units5',
            field=models.IntegerField(blank=True, null=True, verbose_name='العدد'),
        ),
        migrations.AddField(
            model_name='billsale',
            name='num_of_units6',
            field=models.IntegerField(blank=True, null=True, verbose_name='العدد'),
        ),
        migrations.AddField(
            model_name='billsale',
            name='price_all2',
            field=models.IntegerField(blank=True, null=True, verbose_name='القيمة'),
        ),
        migrations.AddField(
            model_name='billsale',
            name='price_all3',
            field=models.IntegerField(blank=True, null=True, verbose_name='القيمة'),
        ),
        migrations.AddField(
            model_name='billsale',
            name='price_all4',
            field=models.IntegerField(blank=True, null=True, verbose_name='القيمة'),
        ),
        migrations.AddField(
            model_name='billsale',
            name='price_all5',
            field=models.IntegerField(blank=True, null=True, verbose_name='القيمة'),
        ),
        migrations.AddField(
            model_name='billsale',
            name='price_all6',
            field=models.IntegerField(blank=True, null=True, verbose_name='القيمة'),
        ),
        migrations.AddField(
            model_name='billsale',
            name='price_of_unit2',
            field=models.IntegerField(blank=True, null=True, verbose_name='سعر الوحدة'),
        ),
        migrations.AddField(
            model_name='billsale',
            name='price_of_unit3',
            field=models.IntegerField(blank=True, null=True, verbose_name='سعر الوحدة'),
        ),
        migrations.AddField(
            model_name='billsale',
            name='price_of_unit4',
            field=models.IntegerField(blank=True, null=True, verbose_name='سعر الوحدة'),
        ),
        migrations.AddField(
            model_name='billsale',
            name='price_of_unit5',
            field=models.IntegerField(blank=True, null=True, verbose_name='سعر الوحدة'),
        ),
        migrations.AddField(
            model_name='billsale',
            name='price_of_unit6',
            field=models.IntegerField(blank=True, null=True, verbose_name='سعر الوحدة'),
        ),
        migrations.AddField(
            model_name='billsale',
            name='unit_of_product2',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='الوحدة'),
        ),
        migrations.AddField(
            model_name='billsale',
            name='unit_of_product3',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='الوحدة'),
        ),
        migrations.AddField(
            model_name='billsale',
            name='unit_of_product4',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='الوحدة'),
        ),
        migrations.AddField(
            model_name='billsale',
            name='unit_of_product5',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='الوحدة'),
        ),
        migrations.AddField(
            model_name='billsale',
            name='unit_of_product6',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='الوحدة'),
        ),
        migrations.AlterField(
            model_name='adddrug',
            name='date_of_entering',
            field=models.DateField(default=datetime.datetime(2023, 5, 6, 10, 32, 7, 287355), verbose_name='تاريخ الإدخال'),
        ),
        migrations.AlterField(
            model_name='billsale',
            name='name_of_product1',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='اسم المنتج'),
        ),
        migrations.AlterField(
            model_name='billsale',
            name='num_bill',
            field=models.CharField(default='9797', max_length=100, verbose_name='رقم الفاتورة'),
        ),
        migrations.AlterField(
            model_name='billsale',
            name='num_of_units1',
            field=models.IntegerField(blank=True, null=True, verbose_name='العدد'),
        ),
        migrations.AlterField(
            model_name='billsale',
            name='price_all1',
            field=models.IntegerField(blank=True, null=True, verbose_name='القيمة'),
        ),
        migrations.AlterField(
            model_name='billsale',
            name='price_of_unit1',
            field=models.IntegerField(blank=True, null=True, verbose_name='سعر الوحدة'),
        ),
        migrations.AlterField(
            model_name='billsale',
            name='unit_of_product1',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='الوحدة'),
        ),
    ]
