# Generated by Django 4.2 on 2023-05-06 22:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_billsale_name_of_product2_billsale_name_of_product3_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billsale',
            name='date_of_bill',
        ),
        migrations.RemoveField(
            model_name='billsale',
            name='name_of_product2',
        ),
        migrations.RemoveField(
            model_name='billsale',
            name='name_of_product3',
        ),
        migrations.RemoveField(
            model_name='billsale',
            name='name_of_product4',
        ),
        migrations.RemoveField(
            model_name='billsale',
            name='name_of_product5',
        ),
        migrations.RemoveField(
            model_name='billsale',
            name='name_of_product6',
        ),
        migrations.RemoveField(
            model_name='billsale',
            name='num_of_units2',
        ),
        migrations.RemoveField(
            model_name='billsale',
            name='num_of_units3',
        ),
        migrations.RemoveField(
            model_name='billsale',
            name='num_of_units4',
        ),
        migrations.RemoveField(
            model_name='billsale',
            name='num_of_units5',
        ),
        migrations.RemoveField(
            model_name='billsale',
            name='num_of_units6',
        ),
        migrations.RemoveField(
            model_name='billsale',
            name='price_all2',
        ),
        migrations.RemoveField(
            model_name='billsale',
            name='price_all3',
        ),
        migrations.RemoveField(
            model_name='billsale',
            name='price_all4',
        ),
        migrations.RemoveField(
            model_name='billsale',
            name='price_all5',
        ),
        migrations.RemoveField(
            model_name='billsale',
            name='price_all6',
        ),
        migrations.RemoveField(
            model_name='billsale',
            name='price_of_unit2',
        ),
        migrations.RemoveField(
            model_name='billsale',
            name='price_of_unit3',
        ),
        migrations.RemoveField(
            model_name='billsale',
            name='price_of_unit4',
        ),
        migrations.RemoveField(
            model_name='billsale',
            name='price_of_unit5',
        ),
        migrations.RemoveField(
            model_name='billsale',
            name='price_of_unit6',
        ),
        migrations.RemoveField(
            model_name='billsale',
            name='time_of_bill',
        ),
        migrations.RemoveField(
            model_name='billsale',
            name='unit_of_product2',
        ),
        migrations.RemoveField(
            model_name='billsale',
            name='unit_of_product3',
        ),
        migrations.RemoveField(
            model_name='billsale',
            name='unit_of_product4',
        ),
        migrations.RemoveField(
            model_name='billsale',
            name='unit_of_product5',
        ),
        migrations.RemoveField(
            model_name='billsale',
            name='unit_of_product6',
        ),
        migrations.AlterField(
            model_name='adddrug',
            name='date_of_entering',
            field=models.DateField(default=datetime.datetime(2023, 5, 6, 17, 46, 34, 832763), verbose_name='تاريخ الإدخال'),
        ),
        migrations.AlterField(
            model_name='billsale',
            name='num_bill',
            field=models.CharField(default='6033', max_length=100, verbose_name='رقم الفاتورة'),
        ),
    ]
