# Generated by Django 4.2 on 2023-05-07 02:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_remove_billsale_date_of_bill_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_product', models.CharField(max_length=100, verbose_name='اسم المنتج')),
                ('unit_of_product', models.CharField(max_length=100, verbose_name='الوحدة')),
                ('price_of_unit', models.IntegerField(verbose_name='سعر الوحدة')),
                ('num_of_units', models.IntegerField(verbose_name='العدد')),
                ('price_all', models.IntegerField(verbose_name='القيمة')),
            ],
        ),
        migrations.AlterField(
            model_name='adddrug',
            name='date_of_entering',
            field=models.DateField(default=datetime.datetime(2023, 5, 6, 21, 34, 55, 52561), verbose_name='تاريخ الإدخال'),
        ),
        migrations.AlterField(
            model_name='billsale',
            name='num_bill',
            field=models.CharField(default='9499', max_length=100, verbose_name='رقم الفاتورة'),
        ),
        migrations.AddField(
            model_name='billsale',
            name='products',
            field=models.ManyToManyField(to='main.product_bill', verbose_name='المنتجات المباعة'),
        ),
    ]
