# Generated by Django 4.2 on 2023-05-07 03:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_product_bill_alter_adddrug_date_of_entering_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billsale',
            name='products',
        ),
        migrations.AddField(
            model_name='product_bill',
            name='num_bill',
            field=models.CharField(default='2285', max_length=100, verbose_name='رقم الفاتورة'),
        ),
        migrations.AlterField(
            model_name='adddrug',
            name='date_of_entering',
            field=models.DateField(default=datetime.datetime(2023, 5, 6, 22, 17, 50, 952550), verbose_name='تاريخ الإدخال'),
        ),
        migrations.AlterField(
            model_name='billsale',
            name='num_bill',
            field=models.CharField(default='2285', max_length=100, verbose_name='رقم الفاتورة'),
        ),
    ]
