# Generated by Django 4.2 on 2023-05-07 18:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_adddrug_date_of_entering_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billsale',
            name='name_of_product1',
        ),
        migrations.RemoveField(
            model_name='billsale',
            name='num_of_units1',
        ),
        migrations.RemoveField(
            model_name='billsale',
            name='price_all1',
        ),
        migrations.RemoveField(
            model_name='billsale',
            name='price_of_unit1',
        ),
        migrations.RemoveField(
            model_name='billsale',
            name='unit_of_product1',
        ),
        migrations.AlterField(
            model_name='adddrug',
            name='date_of_entering',
            field=models.DateField(default=datetime.datetime(2023, 5, 7, 13, 28, 17, 659409), verbose_name='تاريخ الإدخال'),
        ),
        migrations.AlterField(
            model_name='billsale',
            name='num_bill',
            field=models.CharField(default='7620', max_length=100, verbose_name='رقم الفاتورة'),
        ),
        migrations.AlterField(
            model_name='product_bill',
            name='num_bill',
            field=models.CharField(default='7620', max_length=100, verbose_name='رقم الفاتورة'),
        ),
    ]
