# Generated by Django 4.2 on 2023-05-07 21:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_adddrug_date_of_entering_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='billsale',
            name='products',
            field=models.ManyToManyField(to='main.product_bill', verbose_name=' المنتجات'),
        ),
        migrations.AlterField(
            model_name='adddrug',
            name='date_of_entering',
            field=models.DateField(default=datetime.datetime(2023, 5, 7, 16, 22, 24, 983218), verbose_name='تاريخ الإدخال'),
        ),
        migrations.AlterField(
            model_name='billsale',
            name='num_bill',
            field=models.CharField(default='6553', max_length=100, verbose_name='رقم الفاتورة'),
        ),
        migrations.AlterField(
            model_name='product_bill',
            name='num_bill',
            field=models.CharField(default='6553', max_length=100, verbose_name='رقم الفاتورة'),
        ),
    ]
