# Generated by Django 4.2 on 2023-05-08 00:01

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_alter_adddrug_date_of_entering_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adddrug',
            name='date_of_entering',
            field=models.DateField(default=datetime.datetime(2023, 5, 7, 19, 1, 28, 927980), verbose_name='تاريخ الإدخال'),
        ),
        migrations.AlterField(
            model_name='billsale',
            name='num_bill',
            field=models.CharField(default='2051', max_length=100, verbose_name='رقم الفاتورة'),
        ),
        migrations.CreateModel(
            name='Product_bills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_bill', models.CharField(default='2051', max_length=100, verbose_name='رقم الفاتورة')),
                ('name_of_product', models.CharField(max_length=100, verbose_name='اسم المنتج')),
                ('unit_of_product', models.CharField(max_length=100, verbose_name='الوحدة')),
                ('price_of_unit', models.IntegerField(verbose_name='سعر الوحدة')),
                ('num_of_units', models.IntegerField(verbose_name='العدد')),
                ('price_all', models.IntegerField(verbose_name='القيمة')),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.billsale', verbose_name='')),
            ],
        ),
    ]
