# Generated by Django 4.2 on 2023-05-08 03:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_product_bill_alter_adddrug_date_of_entering_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_bill',
            name='products',
        ),
        migrations.AlterField(
            model_name='adddrug',
            name='date_of_entering',
            field=models.DateField(default=datetime.datetime(2023, 5, 7, 22, 37, 42, 593713), verbose_name='تاريخ الإدخال'),
        ),
        migrations.DeleteModel(
            name='Billsale',
        ),
        migrations.DeleteModel(
            name='Product_bill',
        ),
    ]
