# Generated by Django 4.2 on 2023-05-08 03:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_remove_product_bill_products_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Billsale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_bill', models.CharField(default='7282', max_length=100, verbose_name='رقم الفاتورة')),
                ('name_of_customer', models.CharField(max_length=100, verbose_name='اسم المشتري')),
                ('allvalue_of_bill', models.IntegerField(verbose_name='قيمة الفاتورة الكلية')),
                ('allvalue_of_bill_after_tax', models.IntegerField(verbose_name=' قيمة الفاتورة الكلية مع الضريبة ')),
                ('taken_money', models.IntegerField(verbose_name='المبلغ المقبوض')),
                ('will_taken_money', models.IntegerField(blank=True, null=True, verbose_name='المبلغ المتبقي')),
                ('cause', models.TextField(blank=True, null=True, verbose_name='السبب')),
                ('date_of_taken_money', models.DateField(blank=True, null=True, verbose_name='وقت استرداد المال')),
                ('cuurency', models.CharField(blank=True, max_length=100, null=True, verbose_name='العملة')),
                ('date', models.DateField(auto_now_add=True, verbose_name='التاريخ')),
            ],
        ),
        migrations.CreateModel(
            name='Product_bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_bill', models.CharField(default='7282', max_length=100, verbose_name='رقم الفاتورة')),
                ('name_of_product', models.CharField(max_length=100, verbose_name='اسم المنتج')),
                ('unit_of_product', models.CharField(max_length=100, verbose_name='الوحدة')),
                ('price_of_unit', models.IntegerField(verbose_name='سعر الوحدة')),
                ('num_of_units', models.IntegerField(verbose_name='العدد')),
                ('price_all', models.IntegerField(verbose_name='القيمة')),
                ('date', models.DateField(auto_now_add=True, verbose_name='التاريخ')),
            ],
        ),
        migrations.AlterField(
            model_name='adddrug',
            name='date_of_entering',
            field=models.DateField(default=datetime.datetime(2023, 5, 7, 22, 38, 25, 164760), verbose_name='تاريخ الإدخال'),
        ),
    ]
