# Generated by Django 4.2 on 2023-05-09 03:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_delete_product_bill_alter_adddrug_date_of_entering_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_bill', models.CharField(default='7898', max_length=100, verbose_name='رقم الفاتورة')),
                ('name_of_customer', models.CharField(max_length=100, verbose_name='اسم المشتري')),
                ('name_of_product', models.CharField(max_length=100, verbose_name='اسم المنتج')),
                ('unit_of_product', models.CharField(max_length=100, verbose_name='الوحدة')),
                ('price_of_unit', models.IntegerField(verbose_name='سعر الوحدة')),
                ('num_of_units', models.IntegerField(verbose_name='العدد')),
                ('price_all', models.IntegerField(verbose_name='القيمة')),
                ('date', models.DateField(auto_now_add=True, verbose_name='التاريخ')),
            ],
        ),
        migrations.AlterField(
            model_name='adddrug',
            name='date_of_entering',
            field=models.DateField(default=datetime.datetime(2023, 5, 8, 22, 23, 41, 93945), verbose_name='تاريخ الإدخال'),
        ),
        migrations.AlterField(
            model_name='billsale',
            name='num_bill',
            field=models.CharField(default='7898', max_length=100, verbose_name='رقم الفاتورة'),
        ),
    ]
