# Generated by Django 4.2 on 2023-05-10 05:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_alter_adddrug_date_of_entering_alter_billsale_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billsale',
            name='date',
        ),
        migrations.RemoveField(
            model_name='product_bills',
            name='date',
        ),
        migrations.AlterField(
            model_name='adddrug',
            name='date_of_entering',
            field=models.DateField(default=datetime.datetime(2023, 5, 10, 0, 58, 30, 50426), verbose_name='تاريخ الإدخال'),
        ),
        migrations.AlterField(
            model_name='billsale',
            name='num_bill',
            field=models.CharField(default='2610', max_length=100, verbose_name='رقم الفاتورة'),
        ),
        migrations.AlterField(
            model_name='product_bills',
            name='num_bill',
            field=models.CharField(default='2610', max_length=100, verbose_name='رقم الفاتورة'),
        ),
    ]
