# Generated by Django 4.2 on 2023-05-10 17:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_remove_billsale_date_remove_product_bills_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billsale',
            old_name='cuurency',
            new_name='curency',
        ),
        migrations.RemoveField(
            model_name='billsale',
            name='date_of_taken_money',
        ),
        migrations.AlterField(
            model_name='adddrug',
            name='date_of_entering',
            field=models.DateField(default=datetime.datetime(2023, 5, 10, 12, 25, 8, 24021), verbose_name='تاريخ الإدخال'),
        ),
        migrations.AlterField(
            model_name='billsale',
            name='num_bill',
            field=models.CharField(max_length=100, verbose_name='رقم الفاتورة'),
        ),
        migrations.AlterField(
            model_name='product_bills',
            name='num_bill',
            field=models.CharField(max_length=100, verbose_name='رقم الفاتورة'),
        ),
    ]
