# Generated by Django 4.2 on 2023-05-11 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_rename_cuurency_billsale_curency_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Adddrug',
        ),
        migrations.DeleteModel(
            name='Billsale',
        ),
        migrations.DeleteModel(
            name='Product_bills',
        ),
    ]
