# Generated by Django 4.2 on 2023-05-11 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Adddrug',
        ),
        migrations.DeleteModel(
            name='Billsale',
        ),
        migrations.DeleteModel(
            name='Product_bills',
        ),
    ]
