# Generated by Django 4.2 on 2023-05-11 14:31

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0038_delete_adddrug_delete_billsale_delete_product_bills'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adddrug',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('time', models.TimeField(auto_now=1, verbose_name='التوقيت')),
                ('product_name', models.CharField(max_length=100, verbose_name='اسم المنتج')),
                ('category', models.CharField(default='', max_length=100, verbose_name='الفئة')),
                ('desc', models.CharField(max_length=500, verbose_name='الوصف')),
                ('currency', models.CharField(max_length=500, verbose_name='العملة')),
                ('unit', models.CharField(blank=True, max_length=100, null=True, verbose_name='الوحدة')),
                ('num_of_unit', models.IntegerField(blank=True, default=0, null=True, verbose_name='عدد الوحدات')),
                ('cost_of_unit', models.IntegerField(blank=True, default=0, null=True, verbose_name='تكلفة الوحدة')),
                ('price_of_unit', models.IntegerField(blank=True, default=0, null=True, verbose_name='سعر الوحدة')),
                ('date_of_entering', models.DateField(default=django.utils.timezone.now, verbose_name='تاريخ الإدخال')),
                ('date_of_ending', models.DateField(verbose_name='تاريخ انتهاء الصلاحية')),
                ('image', models.ImageField(blank=True, null=True, upload_to='photoproduct/%y/%m/%d', verbose_name='صورة المنتج')),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'drug',
                'verbose_name_plural': 'drugs',
            },
        ),
        migrations.CreateModel(
            name='Billsale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_bill', models.CharField(max_length=100, verbose_name='رقم الفاتورة')),
                ('name_of_customer', models.CharField(max_length=100, verbose_name='اسم المشتري')),
                ('allvalue_of_bill', models.IntegerField(verbose_name='قيمة الفاتورة الكلية')),
                ('allvalue_of_bill_after_tax', models.IntegerField(verbose_name=' قيمة الفاتورة الكلية مع الضريبة ')),
                ('taken_money', models.IntegerField(verbose_name='المبلغ المقبوض')),
                ('will_taken_money', models.IntegerField(blank=True, null=True, verbose_name='المبلغ المتبقي')),
                ('cause', models.TextField(blank=True, null=True, verbose_name='السبب')),
                ('date_of_taken_money', models.DateField(blank=True, null=True, verbose_name='وقت استرداد المال')),
                ('curency', models.CharField(blank=True, max_length=100, null=True, verbose_name='العملة')),
                ('date', models.DateField(verbose_name='التاريخ')),
                ('day', models.DateField(verbose_name='اليوم')),
                ('month', models.DateField(verbose_name='الشهر')),
                ('year', models.DateField(verbose_name='السنة')),
                ('time', models.TimeField(verbose_name='التوقيت')),
            ],
        ),
        migrations.CreateModel(
            name='Product_bills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_bill', models.CharField(max_length=100, verbose_name='رقم الفاتورة')),
                ('name_of_customer', models.CharField(max_length=100, verbose_name='اسم المشتري')),
                ('name_of_product', models.CharField(max_length=100, verbose_name='اسم المنتج')),
                ('unit_of_product', models.CharField(max_length=100, verbose_name='الوحدة')),
                ('price_of_unit', models.IntegerField(verbose_name='سعر الوحدة')),
                ('num_of_units', models.IntegerField(verbose_name='العدد')),
                ('price_all', models.IntegerField(verbose_name='القيمة')),
                ('date', models.DateField(default=datetime.datetime(2023, 5, 11, 9, 31, 21, 603699), verbose_name='التاريخ')),
                ('day', models.DateField(default=11, verbose_name='اليوم')),
                ('month', models.DateField(default=5, verbose_name='الشهر')),
                ('year', models.DateField(default=2023, verbose_name='السنة')),
                ('time', models.TimeField(verbose_name='التوقيت')),
            ],
        ),
    ]
