# Generated by Django 4.2 on 2023-05-11 14:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0039_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billsale',
            name='day',
            field=models.CharField(max_length=100, verbose_name='اليوم'),
        ),
        migrations.AlterField(
            model_name='billsale',
            name='month',
            field=models.CharField(max_length=100, verbose_name='الشهر'),
        ),
        migrations.AlterField(
            model_name='billsale',
            name='year',
            field=models.CharField(max_length=100, verbose_name='السنة'),
        ),
        migrations.AlterField(
            model_name='product_bills',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 5, 11, 9, 58, 57, 838697), verbose_name='التاريخ'),
        ),
        migrations.AlterField(
            model_name='product_bills',
            name='day',
            field=models.CharField(max_length=100, verbose_name='اليوم'),
        ),
        migrations.AlterField(
            model_name='product_bills',
            name='month',
            field=models.CharField(max_length=100, verbose_name='الشهر'),
        ),
        migrations.AlterField(
            model_name='product_bills',
            name='year',
            field=models.CharField(max_length=100, verbose_name='السنة'),
        ),
    ]
