# Generated by Django 4.2 on 2023-05-14 17:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0040_alter_billsale_day_alter_billsale_month_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('money', models.IntegerField(verbose_name='المال الداخل')),
                ('direction', models.CharField(max_length=100, verbose_name='الاتجاه')),
                ('date', models.DateField(verbose_name='التاريخ')),
                ('day', models.CharField(max_length=100, verbose_name='اليوم')),
                ('month', models.CharField(max_length=100, verbose_name='الشهر')),
                ('year', models.CharField(max_length=100, verbose_name='السنة')),
                ('time', models.TimeField(verbose_name='التوقيت')),
                ('num_bill', models.CharField(max_length=100, verbose_name='رقم الفاتورة')),
            ],
        ),
        migrations.AlterField(
            model_name='billsale',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 5, 14, 12, 30, 24, 995748), verbose_name='التاريخ'),
        ),
        migrations.AlterField(
            model_name='product_bills',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 5, 14, 12, 30, 24, 995748), verbose_name='التاريخ'),
        ),
    ]
