# Generated by Django 4.2 on 2023-05-14 21:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0041_box_alter_billsale_date_alter_product_bills_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billsale',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 5, 14, 16, 55, 42, 482760), verbose_name='التاريخ'),
        ),
        migrations.AlterField(
            model_name='product_bills',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 5, 14, 16, 55, 42, 482760), verbose_name='التاريخ'),
        ),
    ]
