# Generated by Django 4.2 on 2023-05-14 22:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0042_alter_billsale_date_alter_product_bills_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Boxnow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('money', models.IntegerField(verbose_name='المال الموحود حالياً')),
            ],
        ),
        migrations.AlterField(
            model_name='billsale',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 5, 14, 17, 29, 10, 628731), verbose_name='التاريخ'),
        ),
        migrations.AlterField(
            model_name='product_bills',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 5, 14, 17, 29, 10, 628731), verbose_name='التاريخ'),
        ),
    ]
