# Generated by Django 4.2 on 2023-05-15 04:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0044_expenses_alter_billsale_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_bill', models.CharField(max_length=100, verbose_name='رقم الفاتورة')),
                ('typebill', models.CharField(max_length=100, verbose_name='نوع الفاتورة')),
                ('money', models.IntegerField(verbose_name='المبلغ')),
                ('date', models.DateField(verbose_name='التاريخ')),
                ('time', models.TimeField(verbose_name='التوقيت')),
            ],
        ),
        migrations.DeleteModel(
            name='Expenses',
        ),
        migrations.AlterField(
            model_name='billsale',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 5, 14, 23, 15, 43, 704757), verbose_name='التاريخ'),
        ),
        migrations.AlterField(
            model_name='product_bills',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 5, 14, 23, 15, 43, 704757), verbose_name='التاريخ'),
        ),
    ]
