# Generated by Django 4.2 on 2023-05-15 04:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0045_expense_delete_expenses_alter_billsale_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billsale',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 5, 14, 23, 37, 41, 639459), verbose_name='التاريخ'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='num_bill',
            field=models.CharField(default='7440', max_length=100, verbose_name='رقم الفاتورة'),
        ),
        migrations.AlterField(
            model_name='product_bills',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 5, 14, 23, 37, 41, 639459), verbose_name='التاريخ'),
        ),
    ]
